# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_imege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imege',
            new_name='image',
        ),
    ]
